server:
  port: 9090


spring:
  cloud:
    gateway:
      routes:
        - id: public-service-api
          uri: http://localhost:8080
          predicates:
            - Path=/service-api/open-api/**
          filters:
            - RewritePath=/server-api(?<segment>/?.*), $\{segment}
            - ServiceApiPublicFilter
      default-filters:
        - name: LoggingFilter
          args:
            baseMessage: 'Global Logging Filter: '
            preLogger: true,
            postLogger: true

