POST http://localhost:8080/api/v1/user
datasource: BUILDER
Content-Type: application/json

{
   "name": "dfefef"
}

###
GET http://localhost:8080/api/v1/user
datasource: BUILDER

###
PATCH http://localhost:8080/api/v1/user?id=1&name=cc
datasource: BUILDER

###
POST http://localhost:8080/api/v1/post
datasource: BUILDER
Content-Type: application/json

{
  "userId": 1,
  "title": "t",
  "content": "t"
}

###
POST http://localhost:8080/api/v1/user/transfer?target=PROD
datasource: BUILDER

###
GET http://localhost:8080/api/v1/user
datasource: PROD
