spring:
  jpa:
    #    hibernate:
    #      ddl-auto: create
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    com:
      zaxxer: trace
    org:
      springframework:
        jdbc: trace
        orm:
          jpa: trace
        transaction:
          interceptor: trace

edc:
  datasource:
    BUILDER:
      url: jdbc:mysql://127.0.0.1:13306/builder
      username: root
      password: admin
    UAT:
      url: jdbc:mysql://127.0.0.1:13306/uat
      username: root
      password: admin
    PROD:
      url: jdbc:mysql://127.0.0.1:13306/prod
      username: root
      password: admin