spring:
  datasource:
    url: jdbc:mysql://localhost:4406/pilot
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

      org:
        hibernate:
          envers:
            audit_table_suffix: _history
