version: '3.2'
services:
  cassandra-node-0:
    image: cassandra
    environment:
      CASSANDRA_SEEDS: cassandra-node-0
      CASSANDRA_CLUSTER_NAME: MyCluster
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_DC: datacenter11
    ports:
      - "7000:7000"
      - "7001:7001"
      - "9042:9042"
#
#
#  cassandra-node-1:
#    image: cassandra
#    environment:
#      CASSANDRA_SEEDS: cassandra-node-0
#      CASSANDRA_CLUSTER_NAME: MyCluster
#      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
#      CASSANDRA_DC: datacenter11
#    ports:
#      - "17000:7000"
#      - "17001:7001"
#      - "19042:9042"
#
#  cassandra-node-2:
#    image: cassandra
#    environment:
#      CASSANDRA_SEEDS: cassandra-node-0
#      CASSANDRA_CLUSTER_NAME: MyCluster
#      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
#      CASSANDRA_DC: datacenter11
#    ports:
#      - "27000:7000"
#      - "27001:7001"
#      - "29042:9042"
